### ISSUE TITLE
Create EtcdInstance failed

### ISSUE THREAD

**Issue by qiyi** [opentable/otj-etcd-embedded#3]
Hello, while i am create the  EtcdInstance, the **`IllegalStateException("Could not find /etcd/etcd-windows10-amd64 on classpath")`** throwed. It seems that on windows 10, the `System.getProperty("os.name")` returns `Windows 10` but not `Windows`

related code:
https://github.com/opentable/otj-etcd-embedded/blob/f3fff5bd9971d802bc3b95d6e0d2fb319f030e1a/src/main/java/com/opentable/etcd/EtcdInstance.java#L55

**Comment by mikebell90** [comment]
Sorry for the late reply. We're not actively using this repo anymore. Please feel free to fork it and modify!
